#!/usr/bin/env python3
"""
Repair the spotDL web interface so it can download what it advertises.

Generated by dev/gen_patch.py - do not hand-edit; regenerate instead.
Base spotdl version: 4.5.2-r2

Applied at image build time on top of the upstream `spotdl/spotify-downloader`
image. Each edit is an anchored, exact-match replacement:

  * anchor present            -> the edit is applied
  * edit already present      -> nothing to do (idempotent)
  * anything else             -> exit non-zero with a message, so the build
                                 FAILS loudly instead of shipping a module that
                                 silently reverted unrelated upstream changes

Fixes
-----
1. Album / playlist / artist URLs. `Song.from_url()` starts with

       if "open.spotify.com" not in url or "track" not in url:
           raise SongError(f"Invalid URL: {url}")

   so every non-track URL is rejected even though `validate_search_term()`
   accepts them, `home.html.j2` advertises them, and `web/api.py` already
   imports `Album`, `Playlist` and `Artist` without using them. URLs now go
   through `spotdl.utils.search.parse_query`, the dispatcher used by
   `spotdl download`.

2. A single unmatched track used to abort the whole album. Tracks download
   independently now, with progress reported per track.

3. Releases whose audio-provider match scores below spotdl's threshold are
   retried once with the similarity filter relaxed. Matching stays strict for
   everything that already resolves.

4. The search box no longer freezes the interface. `get_search_results` blocks
   and was called straight from an `async def` handler, so the single uvicorn
   event loop stalled for as long as Spotify took - minutes - and every page in
   the UI went unreachable. It now runs in a worker thread. The url branch of
   the same handler gains the missing `return`, so a download is not followed by
   a pointless Spotify search for the url string and an empty result list being
   patched into a page the browser has already left.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

VERSION = "4.5.2-r2"

RULES: dict[str, list[tuple[str, str]]] = {}

RULES['web/routes.py'] = [
    (
        r'''import uuid
from pathlib import Path
from typing import Any, Optional, cast
''',
        r'''import html
import re
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional, cast
''',
    ),
    (
        r'''from spotdl.utils.search import get_search_results
''',
        r'''from spotdl.utils.search import get_search_results, parse_query
''',
    ),
    (
        r'''    songs = get_search_results(signals.search_term)
''',
        r'''        # The url has been handled, and downloading it was the entire point of
        # this request. Upstream falls through instead: it spends a Spotify
        # search call on the url string - which matches nothing - and then
        # patches an empty result list into a page the browser has already been
        # redirected away from. Cheap, but pointless, and it can surface an
        # error after a download that actually succeeded.
        return

    # Searching is slow: one Spotify query, then one `Song.from_url` per hit.
    # Called directly it blocks the single uvicorn event loop, which makes every
    # page in the interface - including this very request - unresponsive until
    # it completes. Run it in a worker thread and keep serving meanwhile.
    try:
        songs = await asyncio.get_running_loop().run_in_executor(
            None, get_search_results, signals.search_term
        )
    except Exception as exception:
        app_state.logger.error(f"Search for {signals.search_term} failed! {exception}")
        raise

''',
    ),
    (
        r'''async def gen_download(signals: Signals):
    """
    Generate the download process for the client.
''',
        r'''def resolve_songs(url: str, settings: Dict[str, Any]) -> List[Song]:
    """
    Resolve any Spotify URL into a list of songs.

    Single track URLs are fetched directly, everything else (album, playlist,
    artist, YouTube links, ...) is resolved through the same query parser the
    console `download` command uses.

    ### Arguments
    - url: The URL to resolve.
    - settings: The client's downloader settings.

    ### Returns
    - List of fully initialized Song objects.
    """

    request = re.sub(r"\/intl-\w+\/", "/", str(url).strip().strip("\"'"))

    if "open.spotify.com" in request and "/track/" in request:
        return [Song.from_url(request)]

    return parse_query(
        [request],
        threads=settings.get("threads", 1),
        use_ytm_data=settings.get("ytm_data", False),
        playlist_numbering=settings.get("playlist_numbering", False),
        album_type=settings.get("album_type"),
        playlist_retain_track_cover=settings.get(
            "playlist_retain_track_cover", False
        ),
    )


async def download_song_with_retry(downloader: Any, song: Song) -> Any:
    """
    Download a single song, retrying once with the result filter disabled.

    The audio providers score every search hit against the Spotify metadata and
    drop anything below their match threshold. Obscure releases, remixes and
    tracks with long parenthesised titles regularly score below it, so a second
    pass that trusts the top audio provider hit recovers most failures without
    weakening matching for songs that already resolve correctly.

    ### Arguments
    - downloader: The client's downloader instance.
    - song: The song to download.

    ### Returns
    - The path of the downloaded file, or `None` when both attempts failed.
    """

    path: Optional[Path] = None

    try:
        _, path = await downloader.pool_download(song)
        if path is not None:
            return path
    except Exception as exception:
        app_state.logger.debug("First attempt failed for %s: %s", song.name, exception)

    providers = list(downloader.audio_providers)
    original = [provider.filter_results for provider in providers]

    try:
        for provider in providers:
            provider.filter_results = False

        app_state.logger.info(
            "Retrying without the result filter: %s", song.display_name
        )
        _, path = await downloader.pool_download(song)
    finally:
        for provider, value in zip(providers, original):
            provider.filter_results = value

    return path


def download_status_element(url: str, inner: str) -> str:
    """
    Build the element that replaces the download button for a given url.

    ### Arguments
    - url: The URL the download was requested for.
    - inner: Markup to render inside the button.

    ### Returns
    - HTML string carrying the same element ID as the original button.
    """

    return (
        f'<button id="download-{html.escape(url, quote=True)}" '
        f'class="btn btn-primary btn-square normal-case">'
        f"{inner}</button>"
    )


async def gen_download(signals: Signals):
    """
    Generate the download process for the client.
''',
    ),
    (
        r'''        # Fetch song metadata
        song = Song.from_url(signals.song_url)
        app_state.logger.info(f"Downloading song: {song}")

        # Download Song
        _, path = await client.downloader.pool_download(song)
        yield SSE.patch_elements(f"""
            <button id="download-{signals.song_url}" class="btn btn-primary btn-square">
                    <iconify-icon icon="clarity:check-line" style="font-size: 24px"></iconify-icon>
                </button>
        """)

        if path is None:
            app_state.logger.error(f"Failure downloading {song.name}")

        # return str(path.absolute())

    except Exception as exception:
        app_state.logger.error(f"Error downloading! {exception}")
''',
        r'''        # Resolve the url into one or many songs. This hits the Spotify API and
        # the audio providers, so it runs off the event loop.
        songs = await asyncio.get_running_loop().run_in_executor(
            None, resolve_songs, signals.song_url, client.downloader_settings
        )
    except Exception as exception:
        app_state.logger.error(f"Error resolving {signals.song_url}! {exception}")
        yield SSE.patch_elements(
            download_status_element(
                signals.song_url,
                '<iconify-icon icon="clarity:error-line" style="font-size: 24px"'
                ' title="Could not resolve URL"></iconify-icon>',
            )
        )
        return

    total = len(songs)
    if total == 0:
        app_state.logger.error(f"No songs found for {signals.song_url}")
        yield SSE.patch_elements(
            download_status_element(
                signals.song_url,
                '<iconify-icon icon="clarity:error-line" style="font-size: 24px"'
                ' title="No songs found"></iconify-icon>',
            )
        )
        return

    app_state.logger.info("Found %s song(s) for %s", total, signals.song_url)

    downloaded = 0
    failed = 0

    for index, song in enumerate(songs, start=1):
        app_state.logger.info(f"Downloading song {index}/{total}: {song}")

        if total > 1:
            yield SSE.patch_elements(
                download_status_element(
                    signals.song_url,
                    f'<span class="text-sm">{downloaded + failed}/{total}</span>',
                )
            )

        try:
            # Download Song
            path = await download_song_with_retry(client.downloader, song)

            if path is None:
                failed += 1
                app_state.logger.error(f"Failure downloading {song.name}")
            else:
                downloaded += 1
        except Exception as exception:
            failed += 1
            app_state.logger.error(f"Error downloading {song.name}! {exception}")

    if failed == 0:
        icon = "clarity:check-line"
    else:
        icon = "clarity:error-line"

    yield SSE.patch_elements(
        download_status_element(
            signals.song_url,
            f'<iconify-icon icon="{icon}" style="font-size: 24px"'
            f' title="{downloaded} downloaded, {failed} failed"></iconify-icon>',
        )
    )

    # return str(path.absolute())

''',
    ),
]

RULES['web/api.py'] = [
    (
        r'''import os
import shutil
from pathlib import Path
''',
        r'''import asyncio
import os
import shutil
from pathlib import Path
''',
    ),
    (
        r'''from spotdl.types.song import Song
''',
        r'''from spotdl.types.song import Song, SongError
''',
    ),
    (
        r'''    Download songs using Song url.
''',
        r'''    Download songs using Song, Album, Playlist or Artist url.
''',
    ),
    (
        r'''    - returns the file path if the song was downloaded.
    """
''',
        r'''    - returns the file path if the song was downloaded, or the directory the
      songs were written to when the url contained more than one track.
    """

    # Local import: `spotdl.web.routes` owns the query helpers, and importing it
    # here keeps the module import order untouched.
    from spotdl.web.routes import download_song_with_retry, resolve_songs
''',
    ),
    (
        r'''        # Fetch song metadata
        song = Song.from_url(url)

        # Download Song
        _, path = await client.downloader.pool_download(song)

        if path is None:
            state.logger.error(f"Failure downloading {song.name}")

            raise HTTPException(
                status_code=500, detail=f"Error downloading: {song.name}"
            )

        return str(path.absolute())
''',
        r'''        # Resolve the url into one or many songs, off the event loop.
        songs = await asyncio.get_running_loop().run_in_executor(
            None, resolve_songs, url, client.downloader_settings
        )

        if not songs:
            raise SongError(f"No songs found for url: {url}")

        state.logger.info("Downloading %s song(s) from %s", len(songs), url)

        paths: List[Path] = []
        errors: List[str] = []

        for song in songs:
            # Download Song
            try:
                path = await download_song_with_retry(client.downloader, song)
            except Exception as exception:
                state.logger.error(f"Error downloading {song.name}! {exception}")
                errors.append(song.name)
                continue

            if path is None:
                state.logger.error(f"Failure downloading {song.name}")
                errors.append(song.name)
                continue

            paths.append(path.absolute())

        if not paths:
            raise HTTPException(
                status_code=500,
                detail=f"Error downloading: {', '.join(errors) or url}",
            )

        if errors:
            state.logger.warning(
                "Downloaded %s of %s song(s) from %s, failed: %s",
                len(paths),
                len(songs),
                url,
                ", ".join(errors),
            )

        if len(paths) > 1:
            return str(paths[-1].parent)

        return str(paths[0])

    except HTTPException:
        raise
''',
    ),
]


def apply(path: Path, rules: list[tuple[str, str]]) -> tuple[int, list[str]]:
    """Apply `rules` to `path`. Returns (applied_count, list_of_problems)."""

    text = path.read_text()
    problems: list[str] = []
    applied = 0

    for number, (anchor, replacement) in enumerate(rules, start=1):
        # Test "already applied" before the anchor: an insertion deliberately
        # borrows context as its anchor, and that anchor survives the edit - so
        # checking the anchor first would re-apply the same insertion forever.
        if replacement in text:
            continue

        hits = text.count(anchor)
        if hits == 1:
            text = text.replace(anchor, replacement, 1)
            applied += 1
            continue
        if hits == 0:
            problems.append(
                f"{path.name}: rule {number} anchor is not present - upstream "
                f"code has drifted. Re-derive the patch with dev/gen_patch.py."
            )
            continue
        problems.append(
            f"{path.name}: rule {number} anchor is ambiguous ({hits} matches)"
        )

    if applied:
        path.write_text(text)
    return applied, problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--spotdl-dir",
        type=Path,
        default=Path("/app/spotdl"),
        help="location of the spotdl package inside the image",
    )
    args = parser.parse_args()

    if not args.spotdl_dir.is_dir():
        print(f"error: {args.spotdl_dir} is not a directory", file=sys.stderr)
        return 2

    failed = False
    for name, rules in RULES.items():
        path = args.spotdl_dir / name
        if not path.is_file():
            print(f"error: {path} not found", file=sys.stderr)
            failed = True
            continue

        applied, problems = apply(path, rules)
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        if problems:
            failed = True
            continue
        print(f"{name}: {'patched' if applied else 'already patched'} "
              f"({applied}/{len(rules)} rules)")

    if failed:
        print(f"spotdl-webui-fixed {VERSION}: patch FAILED - do not ship this",
              file=sys.stderr)
        return 1

    print(f"spotdl-webui-fixed {VERSION}: patch OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
